'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace SubzeroSolutions.DotNetNuke.SkinObjects

    Partial Public Class QRCode

        '''<summary>
        '''qrImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents qrImage As Global.System.Web.UI.WebControls.Image
    End Class
End Namespace
